<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-06-06T13:16:23 ART" name="Suite" finished-at="2022-06-06T13:16:47 ART" duration-ms="24098">
    <groups>
    </groups>
    <test started-at="2022-06-06T13:16:23 ART" name="Test" finished-at="2022-06-06T13:16:47 ART" duration-ms="24098">
      <class name="example.NewTest">
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:example.NewTest@7ec7ffd3]" started-at="2022-06-06T13:16:23 ART" name="beforeTest" finished-at="2022-06-06T13:16:25 ART" duration-ms="2251" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method signature="WindowsLogon_01()[pri:10, instance:example.NewTest@7ec7ffd3]" started-at="2022-06-06T13:16:25 ART" name="WindowsLogon_01" finished-at="2022-06-06T13:16:43 ART" duration-ms="17547" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- WindowsLogon_01 -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:example.NewTest@7ec7ffd3]" started-at="2022-06-06T13:16:43 ART" name="afterTest" finished-at="2022-06-06T13:16:43 ART" duration-ms="244" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:example.NewTest@7ec7ffd3]" started-at="2022-06-06T13:16:43 ART" name="beforeTest" finished-at="2022-06-06T13:16:44 ART" duration-ms="989" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method signature="WindowsLogon_02()[pri:11, instance:example.NewTest@7ec7ffd3]" started-at="2022-06-06T13:16:44 ART" name="WindowsLogon_02" finished-at="2022-06-06T13:16:46 ART" duration-ms="1494" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login user as espected expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login user as espected expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at example.NewTest.WindowsLogon_02(NewTest.java:130)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- WindowsLogon_02 -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:example.NewTest@7ec7ffd3]" started-at="2022-06-06T13:16:46 ART" name="afterTest" finished-at="2022-06-06T13:16:46 ART" duration-ms="155" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:example.NewTest@7ec7ffd3]" started-at="2022-06-06T13:16:46 ART" name="beforeTest" finished-at="2022-06-06T13:16:47 ART" duration-ms="866" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method signature="testEasy()[pri:20, instance:example.NewTest@7ec7ffd3]" started-at="2022-06-06T13:16:47 ART" name="testEasy" finished-at="2022-06-06T13:16:47 ART" duration-ms="300" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEasy -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:example.NewTest@7ec7ffd3]" started-at="2022-06-06T13:16:47 ART" name="afterTest" finished-at="2022-06-06T13:16:47 ART" duration-ms="194" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- example.NewTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
